INSERT INTO `t_category` VALUES('23','1','content','0','3','0','0','0','23','在线提问管理','','','','','share','http://localhost/index.php?m=content&c=index&a=lists&catid=23','5','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_picture\',
  \'list_template\' => \'list_picture\',
  \'show_template\' => \'show_picture\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','23','1','0','zaixiantiwenguanli','');
