DROP TABLE IF EXISTS `phpcms_storage`;
CREATE TABLE IF NOT EXISTS `phpcms_storage` (
  `aid` smallint(4) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `title` char(80) NOT NULL,
  `isdefault` smallint(1) unsigned NOT NULL DEFAULT '0',
  `username` varchar(40) NOT NULL,
  `addtime` int(10) unsigned NOT NULL DEFAULT '0',
  `area` int(10) unsigned NOT NULL DEFAULT '0',
  `storagename` varchar(100) NOT NULL,
  `storagecode` varchar(50) NOT NULL ,
  `currency` int(10) unsigned NOT NULL DEFAULT '0',
  `instoragefee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `savestoragefee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `changestoragefee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `operatefee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `address` varchar(250) NOT NULL,
  `city` varchar(40) NOT NULL,
  `province` varchar(40) NOT NULL,
  `zipcode` varchar(10) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `listorder` int(10) unsigned NOT NULL DEFAULT '0',
  `note` varchar(250) NOT NULL,
  `jihuodian` smallint(1) unsigned NOT NULL DEFAULT '0',
  `zhongzhuandian` smallint(1) unsigned NOT NULL DEFAULT '0',
  `paifadian` smallint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`aid`),
  KEY `siteid` (`siteid`)
) TYPE=MyISAM ;