DROP TABLE IF EXISTS `phpcms_shipline`;
CREATE TABLE IF NOT EXISTS `phpcms_shipline` (
  `aid` smallint(4) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `title` char(80) NOT NULL,
  `username` varchar(40) NOT NULL,
  `addtime` int(10) unsigned NOT NULL DEFAULT '0',
  `support` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `code` varchar(30) NOT NULL ,
  `origin` int(10) unsigned NOT NULL DEFAULT '0',
  `destination` int(10) unsigned NOT NULL DEFAULT '0',
  `weight` int(10) unsigned NOT NULL DEFAULT '0',
  `currency` int(10) unsigned NOT NULL DEFAULT '0',
  `firstweight` int(10) unsigned NOT NULL DEFAULT '0',
  `addweight` int(10) unsigned NOT NULL DEFAULT '0',
  `heavyvolume` int(10) unsigned NOT NULL DEFAULT '0',
  `volumeprice` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `minweight` int(10) unsigned NOT NULL DEFAULT '0',
  `minprice` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `maxweight` int(10) unsigned NOT NULL DEFAULT '0',
  `freeweight` int(10) unsigned NOT NULL DEFAULT '0',
  `price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `addprice` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `discount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `addoption` varchar(100) NOT NULL,
  `content`  text NOT NULL,
  `mustagree` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `usepoints` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `agreement`  text NOT NULL,
  `listorder` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`aid`),
  KEY `siteid` (`siteid`,`support`)
) TYPE=MyISAM ;