<?php
return array (
  0 => 
  array (
    'aid' => '2',
    'siteid' => '1',
    'title' => 'SAL经济快递',
    'username' => 'admin',
    'addtime' => '1381978429',
    'support' => '0',
    'code' => 'SAL',
    'origin' => '3373',
    'destination' => '1',
    'weight' => '97',
    'currency' => '6',
    'firstweight' => '1',
    'addweight' => '1',
    'heavyvolume' => '0',
    'volumeprice' => '0.00',
    'minweight' => '0',
    'minprice' => '0.00',
    'maxweight' => '30',
    'freeweight' => '0',
    'price' => '0.00',
    'addprice' => '0.00',
    'discount' => '1.00',
    'addoption' => '无',
    'content' => '',
    'mustagree' => '0',
    'usepoints' => '0',
    'agreement' => '0',
    'listorder' => '3',
  ),
  1 => 
  array (
    'aid' => '3',
    'siteid' => '1',
    'title' => 'AIR航空快递',
    'username' => 'admin',
    'addtime' => '1384093448',
    'support' => '0',
    'code' => '航空',
    'origin' => '3373',
    'destination' => '1',
    'weight' => '97',
    'currency' => '6',
    'firstweight' => '1',
    'addweight' => '1',
    'heavyvolume' => '2',
    'volumeprice' => '0.00',
    'minweight' => '0',
    'minprice' => '0.00',
    'maxweight' => '30',
    'freeweight' => '0',
    'price' => '0.00',
    'addprice' => '0.00',
    'discount' => '1.00',
    'addoption' => '',
    'content' => '',
    'mustagree' => '0',
    'usepoints' => '0',
    'agreement' => '',
    'listorder' => '2',
  ),
  2 => 
  array (
    'aid' => '4',
    'siteid' => '1',
    'title' => 'EMS',
    'username' => 'admin',
    'addtime' => '1411582778',
    'support' => '0',
    'code' => 'EMS',
    'origin' => '3373',
    'destination' => '1',
    'weight' => '97',
    'currency' => '6',
    'firstweight' => '1',
    'addweight' => '1',
    'heavyvolume' => '0',
    'volumeprice' => '0.00',
    'minweight' => '0',
    'minprice' => '0.00',
    'maxweight' => '30',
    'freeweight' => '0',
    'price' => '0.00',
    'addprice' => '0.00',
    'discount' => '1.00',
    'addoption' => '',
    'content' => '',
    'mustagree' => '0',
    'usepoints' => '0',
    'agreement' => '',
    'listorder' => '1',
  ),
  3 => 
  array (
    'aid' => '8',
    'siteid' => '1',
    'title' => '海运',
    'username' => 'admin',
    'addtime' => '1418011707',
    'support' => '0',
    'code' => '海运',
    'origin' => '3373',
    'destination' => '1',
    'weight' => '97',
    'currency' => '6',
    'firstweight' => '0',
    'addweight' => '0',
    'heavyvolume' => '0',
    'volumeprice' => '0.00',
    'minweight' => '0',
    'minprice' => '0.00',
    'maxweight' => '0',
    'freeweight' => '0',
    'price' => '0.00',
    'addprice' => '0.00',
    'discount' => '1.00',
    'addoption' => '',
    'content' => '',
    'mustagree' => '0',
    'usepoints' => '0',
    'agreement' => '',
    'listorder' => '4',
  ),
);
?>