<?php
return array (
  0 => 
  array (
    'aid' => '5',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '公斤',
    'value' => 'KG',
    'username' => 'admin',
    'addtime' => '1381978774',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  1 => 
  array (
    'aid' => '16',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '箱',
    'value' => '箱',
    'username' => 'admin',
    'addtime' => '1382586418',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  2 => 
  array (
    'aid' => '17',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '件',
    'value' => '件',
    'username' => 'admin',
    'addtime' => '1382586487',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  3 => 
  array (
    'aid' => '18',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '张',
    'value' => '张',
    'username' => 'admin',
    'addtime' => '1382586508',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  4 => 
  array (
    'aid' => '19',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '个',
    'value' => '个',
    'username' => 'admin',
    'addtime' => '1382586516',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  5 => 
  array (
    'aid' => '61',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '元',
    'value' => '元',
    'username' => 'admin',
    'addtime' => '1385531064',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  6 => 
  array (
    'aid' => '97',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '克',
    'value' => 'G',
    'username' => 'admin',
    'addtime' => '1417749681',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  7 => 
  array (
    'aid' => '94',
    'siteid' => '1',
    'groupid' => '2',
    'title' => '円',
    'value' => 'LBS',
    'username' => 'admin',
    'addtime' => '1414916906',
    'listorder' => '0',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
);
?>