<?php
return array (
  0 => 
  array (
    'aid' => '85',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '未入库',
    'value' => '1',
    'username' => 'admin',
    'addtime' => '1409207844',
    'listorder' => '1',
    'issystem' => '0',
    'remark' => '未入库',
    'country' => '',
  ),
  1 => 
  array (
    'aid' => '86',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '已入库',
    'value' => '3',
    'username' => 'admin',
    'addtime' => '1409207862',
    'listorder' => '2',
    'issystem' => '0',
    'remark' => '已入库',
    'country' => '',
  ),
  2 => 
  array (
    'aid' => '122',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '待处理',
    'value' => '21',
    'username' => 'admin',
    'addtime' => '1420446254',
    'listorder' => '3',
    'issystem' => '0',
    'remark' => '待处理',
    'country' => '',
  ),
  3 => 
  array (
    'aid' => '119',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '未付款',
    'value' => '8',
    'username' => 'admin',
    'addtime' => '1420446114',
    'listorder' => '4',
    'issystem' => '0',
    'remark' => '未付款',
    'country' => '',
  ),
  4 => 
  array (
    'aid' => '87',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '已付款，等待发出',
    'value' => '7',
    'username' => 'admin',
    'addtime' => '1409207880',
    'listorder' => '5',
    'issystem' => '0',
    'remark' => '已付款，等待发出',
    'country' => '',
  ),
  5 => 
  array (
    'aid' => '91',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '已发货',
    'value' => '14',
    'username' => 'admin',
    'addtime' => '1409207950',
    'listorder' => '6',
    'issystem' => '0',
    'remark' => '已发货:',
    'country' => '',
  ),
  6 => 
  array (
    'aid' => '120',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '已分箱',
    'value' => '19',
    'username' => 'admin',
    'addtime' => '1420446233',
    'listorder' => '19',
    'issystem' => '0',
    'remark' => '已分箱',
    'country' => '',
  ),
  7 => 
  array (
    'aid' => '121',
    'siteid' => '1',
    'groupid' => '52',
    'title' => '已合箱',
    'value' => '20',
    'username' => 'admin',
    'addtime' => '1420446244',
    'listorder' => '20',
    'issystem' => '0',
    'remark' => '已合箱',
    'country' => '',
  ),
);
?>