<?php
return array (
  0 => 
  array (
    'aid' => '25',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '未入库',
    'value' => '1',
    'username' => 'admin',
    'addtime' => '1383113142',
    'listorder' => '1',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  1 => 
  array (
    'aid' => '26',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已入库',
    'value' => '3',
    'username' => 'admin',
    'addtime' => '1383113178',
    'listorder' => '3',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  2 => 
  array (
    'aid' => '95',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '待处理',
    'value' => '21',
    'username' => 'admin',
    'addtime' => '1415585340',
    'listorder' => '3',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  3 => 
  array (
    'aid' => '27',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已处理',
    'value' => '4',
    'username' => 'admin',
    'addtime' => '1383113189',
    'listorder' => '4',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  4 => 
  array (
    'aid' => '28',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '问题件',
    'value' => '5',
    'username' => 'admin',
    'addtime' => '1383113201',
    'listorder' => '5',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  5 => 
  array (
    'aid' => '29',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已取消',
    'value' => '6',
    'username' => 'admin',
    'addtime' => '1383113210',
    'listorder' => '6',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  6 => 
  array (
    'aid' => '31',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '未付款',
    'value' => '8',
    'username' => 'admin',
    'addtime' => '1383113227',
    'listorder' => '7',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  7 => 
  array (
    'aid' => '30',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已付款',
    'value' => '7',
    'username' => 'admin',
    'addtime' => '1383113219',
    'listorder' => '8',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  8 => 
  array (
    'aid' => '33',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '待出货',
    'value' => '10',
    'username' => 'admin',
    'addtime' => '1383113242',
    'listorder' => '9',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  9 => 
  array (
    'aid' => '34',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已退件',
    'value' => '11',
    'username' => 'admin',
    'addtime' => '1383113280',
    'listorder' => '11',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  10 => 
  array (
    'aid' => '36',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '等待自取',
    'value' => '13',
    'username' => 'admin',
    'addtime' => '1383113297',
    'listorder' => '13',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  11 => 
  array (
    'aid' => '37',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已发货',
    'value' => '14',
    'username' => 'admin',
    'addtime' => '1383113312',
    'listorder' => '14',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  12 => 
  array (
    'aid' => '46',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '待退件',
    'value' => '15',
    'username' => 'admin',
    'addtime' => '1383365116',
    'listorder' => '15',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  13 => 
  array (
    'aid' => '47',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已签收',
    'value' => '16',
    'username' => 'admin',
    'addtime' => '1383365132',
    'listorder' => '16',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  14 => 
  array (
    'aid' => '80',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已弃件',
    'value' => '18',
    'username' => 'admin',
    'addtime' => '1405669836',
    'listorder' => '18',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
  15 => 
  array (
    'aid' => '92',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已分箱',
    'value' => '19',
    'username' => 'admin',
    'addtime' => '1414859644',
    'listorder' => '19',
    'issystem' => '0',
    'remark' => '1',
    'country' => '',
  ),
  16 => 
  array (
    'aid' => '93',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '已合箱',
    'value' => '20',
    'username' => 'admin',
    'addtime' => '1414859659',
    'listorder' => '20',
    'issystem' => '0',
    'remark' => '1',
    'country' => '',
  ),
  17 => 
  array (
    'aid' => '68',
    'siteid' => '1',
    'groupid' => '9',
    'title' => '回收站',
    'value' => '99',
    'username' => 'admin',
    'addtime' => '1386748244',
    'listorder' => '99',
    'issystem' => '0',
    'remark' => '',
    'country' => '',
  ),
);
?>